### ISSUE TITLE
🦢 Loose Goose November 2024 Content Creation Hub

### ISSUE THREAD

**Issue by blackgirlbytes** [block-open-source/goose-plugins#32]
# 📦 Loose Goose November 2024 Content Creation Hub
20 days filled of AI exploration 🤖, open source 🤝, content creation 📹 and oh yes... prizes!! 

And Block fam - we've seen all of your amazing AI experiments and Goose implementations. So this is your chance to share them with our wider community! :goose:

- Share your experimentation through:
- Blog posts about Goose use cases
- Tutorials on your favorite features
- Videos of your AI experiments

🎁 Top 3 contributors on our [leaderboard](https://github.com/block-open-source/goose-plugins/issues/46) will win $150 gift cards on Amazon! 🎁

## 🚀 Goal
[block-open-source.github.io/goose-plugins](https://block-open-source.github.io/goose-plugins/) is our community content showcase for Goose. We've created this hub of content creation tasks for the community to share their experiences and help others learn about Goose.

## **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.

### 💻 Code
- [ ] #61 
- [x] #62
- [x] #64 
- [x] #74 
- [ ] #75
- [ ] #79 

### 📝 Blog Posts
- [ ] #24 
- [x] #28 
- [x] #31 
- [x] #20 
- [ ] #37 
- [x] #41 
- [x] #49 
- [ ] #55 
- [x] #58 

### 📱 Short-form Videos
- [ ] #27 
- [x] #30 
- [x] #23 
- [ ] #35 
- [ ] #39 
- [x] #43 

### 🎥 Videos
- [ ] #25
- [ ] #29 
- [ ] #22
- [ ] #34 
- [ ] #38 
- [ ] #42 

### 🌐 Social Posts
- [x] #26
- [x] #21 
- [x] #33 
- [x] #36 
- [x] #44 
- [x] #40 

## Examples
https://github.com/user-attachments/assets/0217fc29-3b0b-4ab5-8a60-2dc53eb2b293 

https://github.com/user-attachments/assets/5497112f-7ebb-4e73-9611-191be6d1934f

## Full episodes on Goose to understand more
[![How to Build an AI-Powered GitHub Action](https://img.youtube.com/vi/lppDgrHY88Y/0.jpg)](https://www.youtube.com/watch?v=lppDgrHY88Y)

[![Upgrade U: Supercharging IntelliJ with an Open Source AI Agent](https://img.youtube.com/vi/Z4jF4SrbY2c/0.jpg)](https://www.youtube.com/watch?v=Z4jF4SrbY2c)

## Getting Started
1. Choose a content task from the list above
2. Comment ".take" on the corresponding issue to get assigned
3. Fork the repository and create a new branch
4. Create your content
5. Submit a PR to add your content to the showcase
6. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on the specific issue!

Happy creating! 🦢

**Comment by Johnnyevans32** [comment]
.take

**Comment by Johnnyevans32** [comment]
hi @blackgirlbytes , could you create one more toolkit issue
